### PR TITLE
Added Kotlin color code in the code snippets (IDE type)

### PR DESCRIPTION
**Pull request by Tobibur**
* Color coded kotlin code snippets
* fixed one indent of a checkbox

### CODE REVIEW

**Comment by levibostian** [comment]
Welcome to Teller-Android, @Tobibur 🎊! Thank you so much for the PR. 

There is a bug in my CI script above, as you can see. I will get that fixed so that we can get it running successfully and get this merged. 

Thank you again, Levi

**Comment by Tobibur** [comment]
Okay, no problem. Thanks for considering my PR. :smiley:

**Comment by levibostian** [comment]
@Tobibur, thank you for waiting. 

I believe I fixed the issue. However, it requires that you create a brand new pull request. Sorry to be a pain. 

Could you do this for me, please? 

1. Merged the updated `development` branch of this project into your `patch-1` branch. 
2. Create a new pull request into the `development` branch of this project. 

I updated the `development` branch with the fixes so you will need to do the above for it to work. 

Thanks for helping me test out my CI system 😄😆!

**Comment by Tobibur** [comment]
Should i do the new pull request like this?
new pull request

**Comment by Tobibur** [comment]
I just made a brand new pull request and the checks passed :smiley:

**Pull request closed without merging**
